spring: 
  application: 
    name: Consumer-Feign

server: 
  port: 9100
  
eureka: 
  client: 
    registry-fetch-interval-seconds: 5  #向服务中心检索服务列表的间隔时间
    service-url: 
      defaultZone: http://localhost:8000/eureka/
